services:
    jvb:
        image: jitsi/jvb:stable
        restart: unless-stopped
        ports:
            # ICE/UDP port for media
            - "10000:10000/udp"
            # HTTP API port
            - "9090:9090"
        volumes:
            - ./custom-jvb.conf:/config/custom-jvb.conf
        environment:
            # Authentication (must match what's configured in prosody)
            - JVB_AUTH_PASSWORD=2wPrOS7k
            - XMPP_SERVER=meet.sonacove.com
            - JVB_MUC_NICKNAME=jvb-instance-1
            - ENABLE_OCTO=true
            - JVB_OCTO_REGION=banglore-1
            - JVB_OCTO_RELAY_ID=jvb-instance-1
        logging:
            driver: json-file
            options:
                tag: "{{.Name}}/{{.ImageName}}/{{.ID}}"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        restart: unless-stopped
        command: ["--config=/etc/otelcol/config.yaml"]
        privileged: true
        volumes:
            - ./otel-config.yaml:/etc/otelcol/config.yaml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro # For hostmetrics that might need it and potentially other future uses
            - /var/lib/docker/containers:/var/lib/docker/containers:ro # Mount Docker log directory
        environment:
            - GC_OTLP_USER=${GC_OTLP_USER}
            - GC_OTLP_PASSWORD=${GC_OTLP_PASSWORD}
            - OTEL_RESOURCE_ATTRIBUTES=host.name=${HOSTNAME_FOR_OTEL} # e.g., host.name=jitsi-server-1
        depends_on:
            - jvb
