---
# Main inventory file for all environments
all:
  children:
    production:
      hosts:
        prod:
          ansible_host: meet.sonacove.com
          ansible_user: ansible
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/ansible
          hostname: prod-server
          environment: production
    staging:
      hosts:
        staj:
          ansible_host: staj.sonacove.com
          ansible_user: ansible
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/ansible
          hostname: staj-server
          environment: staging
    site:
      children:
        production:
        staging:
