services:
  jvb:
    image: jitsi/jvb:stable
    container_name: jvb
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/debug?full=true || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    expose:
      # Private API for control and metrics
      - "8080"
    ports:
      # ICE/UDP port for media
      - "10000:10000/udp"
      # Expose colibri websocket for direct access
      - "9090:9090"
    volumes:
      - ./custom-jvb.conf:/tmp/custom-conf.tpl:ro # Mount template file
      - ./custom-logging.properties:/defaults/logging.properties:ro
      - ../entrypoint.sh:/tmp/entrypoint.sh:ro # Mount the entrypoint script
      - ../.env:/tmp/env-file:ro # Mount the env file
    entrypoint: ["sh", "/tmp/entrypoint.sh"]
    environment:
      - CONFIG_OUTPUT_PATH=/config/custom-jvb.conf

      - JVB_AUTH_PASSWORD="defined_in_custom_conf"
      # Env file is mounted and values loaded by entrypoint script
      # We dont need to define anything here
    networks:
      - jvb-network

networks:
  jvb-network:
    driver: bridge
