services:
  jvb:
    image: jitsi/jvb:stable
    container_name: jvb
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/debug?full=true || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./custom-jvb.conf:/defaults/jvb.conf:ro
      - ./custom-logging.properties:/defaults/logging.properties:ro
    environment:
      - XMPP_SERVER=${XMPP_DOMAIN}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_MUC_NICKNAME=${JVB_MUC_NICKNAME}
      - JVB_ADVERTISE_IPS=${JVB_ADVERTISE_IPS}
      - JVB_INSTANCE_ID=${JVB_INSTANCE_ID}
      - JVB_OCTO_REGION=${JVB_OCTO_REGION}
      # LOCAL_ADDRESS calculated by entry script.
    ports:
      # ICE/UDP port for media
      - "10000:10000/udp"
      # Expose colibri websocket for direct access
      - "9090:9090"
    expose:
      # Private API for control and metrics
      - "8080"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
