services:
  prosody:
    image: jitsi/prosody:stable
    container_name: prosody
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5280/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      # Override the default plugins with our own
      - ../prosody-plugins/token/util.lib.lua:/prosody-plugins/token/util.lib.lua
      - ../prosody-plugins/luajwtjitsi.lib.lua:/prosody-plugins/luajwtjitsi.lib.lua
      - ../prosody-plugins/custom:/prosody-plugins-custom
      # Persistent storage for prosody data
      - prosody-data:/config/data
      # Certificates
      - ./certs:/config/certs
      - ./custom-prosodyBase.cfg.lua:/defaults/prosody.cfg.lua:ro
      - ./custom-prosody.cfg.lua:/tmp/custom-conf.tpl:ro
      - ../entrypoint.sh:/tmp/entrypoint.sh:ro
      - ../.env:/tmp/env-file:ro
    entrypoint: ["sh", "/tmp/entrypoint.sh"]
    environment:
      # Override default config because we can't guarantee the order of Include statements
      - CONFIG_OUTPUT_PATH=/defaults/conf.d/jitsi-meet.cfg.lua

      - PROSODY_MODE="client"
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      # Domain configuration (needed for registering the components and traefik labels)
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
      - JVB_AUTH_USER=jvb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"

      # Router for HTTP-BIND (Prosody)
      - "traefik.http.routers.prosody-http-bind.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/http-bind`)"
      - "traefik.http.routers.prosody-http-bind.entrypoints=websecure"
      - "traefik.http.routers.prosody-http-bind.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-http-bind.service=prosody-http-bind-svc"
      - "traefik.http.services.prosody-http-bind-svc.loadbalancer.server.port=5280"

      # Router for XMPP-WebSocket (Prosody)
      - "traefik.http.routers.prosody-xmpp-ws.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/xmpp-websocket`)"
      - "traefik.http.routers.prosody-xmpp-ws.entrypoints=websecure"
      - "traefik.http.routers.prosody-xmpp-ws.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-xmpp-ws.service=prosody-xmpp-ws-svc"
      - "traefik.http.services.prosody-xmpp-ws-svc.loadbalancer.server.port=5280"

      # Router for Room Info API (Prosody)
      - "traefik.http.routers.prosody-room-info.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/_api/room-info`)"
      - "traefik.http.routers.prosody-room-info.entrypoints=websecure"
      - "traefik.http.routers.prosody-room-info.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-room-info.middlewares=prosody-room-info-rewrite@file"
      - "traefik.http.routers.prosody-room-info.service=prosody-room-info-svc"
      - "traefik.http.services.prosody-room-info-svc.loadbalancer.server.port=5280"
    ports:
      # XMPP TCP client port
      - "5222:5222"
    expose:
      # - "5269"  # S2S
      - "5347"  # Component protocol
      # XMPP client port proxied by traefik (BOSH, Websockets)
      - "5280"
    networks:
      - proxy-network

  jicofo:
    image: jitsi/jicofo:stable
    container_name: jicofo
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8888/about/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - prosody
      # Start along with prosody, so its ready when prosody entrypoint script
      # runs the mod_roster_command subscribe focus... command
    volumes:
      - ./custom-jicofo.conf:/tmp/custom-conf.tpl:ro
      - ./custom-logging.properties:/defaults/logging.properties:ro
      - ../entrypoint.sh:/tmp/entrypoint.sh:ro
      - ../.env:/tmp/env-file:ro
    entrypoint: ["sh", "/tmp/entrypoint.sh"]
    environment:
      - CONFIG_OUTPUT_PATH=/config/custom-jicofo.conf

      - JICOFO_AUTH_PASSWORD="defaultpassword"
      - XMPP_HIDDEN_DOMAIN=""
      - XMPP_DOMAIN=${XMPP_DOMAIN} # For traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"

      # Router for Jicofo Conference Request API
      - "traefik.http.routers.jicofo-conf-req.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/conference-request/v1`)"
      - "traefik.http.routers.jicofo-conf-req.entrypoints=websecure"
      - "traefik.http.routers.jicofo-conf-req.tls.certresolver=myresolver"
      - "traefik.http.routers.jicofo-conf-req.middlewares=jicofo-specific-headers@file"
      - "traefik.http.routers.jicofo-conf-req.service=jicofo-conf-req-svc"
      - "traefik.http.services.jicofo-conf-req-svc.loadbalancer.server.port=8888"
    expose:
      # REST including metrics, conference-request, etc.
      - "8888"
    networks:
      - proxy-network

volumes:
  prosody-data:

networks:
  proxy-network:
    external: true
