services:
  # XMPP Server
  prosody:
    image: jitsi/prosody:stable-10431
    container_name: prosody
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5280/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      # Override the default plugins with our own
      - ../prosody-plugins/token/util.lib.lua:/prosody-plugins/token/util.lib.lua:ro
      - ../prosody-plugins/luajwtjitsi.lib.lua:/prosody-plugins/luajwtjitsi.lib.lua:ro
      - ../prosody-plugins/mod_reservations.lua:/prosody-plugins/mod_reservations.lua:ro
      - ../prosody-plugins/custom:/prosody-plugins-custom:ro
      - prosody-data:/config/data
      - ./certs:/config/certs
      - ./custom-prosodyBase.cfg.lua:/defaults/prosody.cfg.lua:ro
      - ./custom-prosody.cfg.lua:/defaults/conf.d/jitsi-meet.cfg.lua:ro
    environment:
      - PROSODY_MODE=client
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_AUTH_USER=jvb
      - PROSODY_TRUSTED_PROXIES_CIDR=${PROSODY_TRUSTED_PROXIES_CIDR:-172.18.0.0/16}
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
      - XMPP_RECORDER_DOMAIN=recorder.${XMPP_DOMAIN}

      - KC_HOST_URL=${KC_HOST_URL}
      - CF_TURN_APP_ID=${CF_TURN_APP_ID}
      - CF_TURN_APP_SECRET=${CF_TURN_APP_SECRET}
    logging:
      driver: json-file
      options:
        labels: "app"
    labels:
      - "app=prosody"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"

      # Router for HTTP-BIND (Prosody)
      - "traefik.http.routers.prosody-http-bind.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/http-bind`)"
      - "traefik.http.routers.prosody-http-bind.entrypoints=websecure"
      - "traefik.http.routers.prosody-http-bind.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-http-bind.service=prosody-http-bind-svc"
      - "traefik.http.services.prosody-http-bind-svc.loadbalancer.server.port=5280"

      # Router for XMPP-WebSocket (Prosody)
      - "traefik.http.routers.prosody-xmpp-ws.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/xmpp-websocket`)"
      - "traefik.http.routers.prosody-xmpp-ws.entrypoints=websecure"
      - "traefik.http.routers.prosody-xmpp-ws.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-xmpp-ws.service=prosody-xmpp-ws-svc"
      - "traefik.http.services.prosody-xmpp-ws-svc.loadbalancer.server.port=5280"

      # Router for Room Info API (Prosody)
      - "traefik.http.routers.prosody-room-info.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/_api/room-info`)"
      - "traefik.http.routers.prosody-room-info.entrypoints=websecure"
      - "traefik.http.routers.prosody-room-info.tls.certresolver=myresolver"
      - "traefik.http.routers.prosody-room-info.middlewares=prosody-room-info-rewrite@docker"
      - "traefik.http.routers.prosody-room-info.service=prosody-room-info-svc"
      - "traefik.http.services.prosody-room-info-svc.loadbalancer.server.port=5280"

      # Prosody-specific middleware for room info API path rewriting
      - "traefik.http.middlewares.prosody-room-info-rewrite.replacepathregex.regex=^/_api/room-info(.*)"
      - "traefik.http.middlewares.prosody-room-info-rewrite.replacepathregex.replacement=/room-info$$1"
    ports:
      # XMPP TCP client port for remote jvbs
      - "5222:5222"
    expose:
      - "5222"
      # - "5269"  # S2S
      - "5347" # Component protocol
      # XMPP client port proxied by traefik (BOSH, Websockets)
      - "5280"
    networks:
      - proxy-network

  # Focus component
  jicofo:
    image: jitsi/jicofo:stable-10431
    container_name: jicofo
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8888/about/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      prosody:
        condition: service_healthy
    volumes:
      - ./custom-jicofo.conf:/defaults/jicofo.conf:ro
      - ./custom-logging.properties:/defaults/logging.properties:ro
    environment:
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - XMPP_RECORDER_DOMAIN=recorder.${XMPP_DOMAIN}
      - JICOFO_OCTO_REGION=${JICOFO_OCTO_REGION}
      - XMPP_DOMAIN=${XMPP_DOMAIN}
    logging:
      driver: json-file
      options:
        labels: "app"
    labels:
      - "app=jicofo"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"

      # Router for Jicofo Conference Request API
      - "traefik.http.routers.jicofo-conf-req.rule=Host(`${XMPP_DOMAIN}`) && PathPrefix(`/conference-request/v1`)"
      - "traefik.http.routers.jicofo-conf-req.entrypoints=websecure"
      - "traefik.http.routers.jicofo-conf-req.tls.certresolver=myresolver"
      - "traefik.http.routers.jicofo-conf-req.middlewares=jicofo-specific-headers@docker"
      - "traefik.http.routers.jicofo-conf-req.service=jicofo-conf-req-svc"
      - "traefik.http.services.jicofo-conf-req-svc.loadbalancer.server.port=8888"

      # Jicofo-specific middleware for CORS and caching headers
      - "traefik.http.middlewares.jicofo-specific-headers.headers.customResponseHeaders.Cache-Control=no-cache, no-store"
      - "traefik.http.middlewares.jicofo-specific-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.jicofo-specific-headers.headers.customResponseHeaders.Access-Control-Allow-Methods=GET, POST, OPTIONS"
      - "traefik.http.middlewares.jicofo-specific-headers.headers.customResponseHeaders.Access-Control-Allow-Headers=DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Content-Type"
    expose:
      # REST including metrics, conference-request, etc.
      - "8888"
    networks:
      - proxy-network

volumes:
  prosody-data:
    name: prosody-data

networks:
  proxy-network:
    external: true
    name: proxy-network
